# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import diagnosis_pb2 as proto_dot_diagnosis__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/diagnosis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiagnosisServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Diagnose = channel.unary_unary(
                '/watchtower.DiagnosisService/Diagnose',
                request_serializer=proto_dot_diagnosis__pb2.DiagnoseRequest.SerializeToString,
                response_deserializer=proto_dot_diagnosis__pb2.DiagnoseResponse.FromString,
                _registered_method=True)
        self.DiagnoseStream = channel.unary_stream(
                '/watchtower.DiagnosisService/DiagnoseStream',
                request_serializer=proto_dot_diagnosis__pb2.DiagnoseRequest.SerializeToString,
                response_deserializer=proto_dot_diagnosis__pb2.DiagnosisStep.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/watchtower.DiagnosisService/HealthCheck',
                request_serializer=proto_dot_diagnosis__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_diagnosis__pb2.HealthResponse.FromString,
                _registered_method=True)


class DiagnosisServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Diagnose(self, request, context):
        """触发 Agent 诊断
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiagnoseStream(self, request, context):
        """流式诊断过程（实时展示 Agent 的调查步骤）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiagnosisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Diagnose': grpc.unary_unary_rpc_method_handler(
                    servicer.Diagnose,
                    request_deserializer=proto_dot_diagnosis__pb2.DiagnoseRequest.FromString,
                    response_serializer=proto_dot_diagnosis__pb2.DiagnoseResponse.SerializeToString,
            ),
            'DiagnoseStream': grpc.unary_stream_rpc_method_handler(
                    servicer.DiagnoseStream,
                    request_deserializer=proto_dot_diagnosis__pb2.DiagnoseRequest.FromString,
                    response_serializer=proto_dot_diagnosis__pb2.DiagnosisStep.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_diagnosis__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_diagnosis__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'watchtower.DiagnosisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('watchtower.DiagnosisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiagnosisService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Diagnose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchtower.DiagnosisService/Diagnose',
            proto_dot_diagnosis__pb2.DiagnoseRequest.SerializeToString,
            proto_dot_diagnosis__pb2.DiagnoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiagnoseStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/watchtower.DiagnosisService/DiagnoseStream',
            proto_dot_diagnosis__pb2.DiagnoseRequest.SerializeToString,
            proto_dot_diagnosis__pb2.DiagnosisStep.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchtower.DiagnosisService/HealthCheck',
            proto_dot_diagnosis__pb2.HealthRequest.SerializeToString,
            proto_dot_diagnosis__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
