// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/diagnosis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagnoseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncidentId       string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Service          string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	AlertDescription string                 `protobuf:"bytes,3,opt,name=alert_description,json=alertDescription,proto3" json:"alert_description,omitempty"`
	Severity         string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	AlertLabels      map[string]string      `protobuf:"bytes,5,rep,name=alert_labels,json=alertLabels,proto3" json:"alert_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RelatedAlerts    []string               `protobuf:"bytes,6,rep,name=related_alerts,json=relatedAlerts,proto3" json:"related_alerts,omitempty"`
	AlertTimestamp   int64                  `protobuf:"varint,7,opt,name=alert_timestamp,json=alertTimestamp,proto3" json:"alert_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiagnoseRequest) Reset() {
	*x = DiagnoseRequest{}
	mi := &file_proto_diagnosis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnoseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseRequest) ProtoMessage() {}

func (x *DiagnoseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnoseRequest.ProtoReflect.Descriptor instead.
func (*DiagnoseRequest) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_proto_rawDescGZIP(), []int{0}
}

func (x *DiagnoseRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *DiagnoseRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DiagnoseRequest) GetAlertDescription() string {
	if x != nil {
		return x.AlertDescription
	}
	return ""
}

func (x *DiagnoseRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *DiagnoseRequest) GetAlertLabels() map[string]string {
	if x != nil {
		return x.AlertLabels
	}
	return nil
}

func (x *DiagnoseRequest) GetRelatedAlerts() []string {
	if x != nil {
		return x.RelatedAlerts
	}
	return nil
}

func (x *DiagnoseRequest) GetAlertTimestamp() int64 {
	if x != nil {
		return x.AlertTimestamp
	}
	return 0
}

type DiagnoseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	RootCause     string                 `protobuf:"bytes,2,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	SuggestedFix  string                 `protobuf:"bytes,5,opt,name=suggested_fix,json=suggestedFix,proto3" json:"suggested_fix,omitempty"`
	AutoFixable   bool                   `protobuf:"varint,6,opt,name=auto_fixable,json=autoFixable,proto3" json:"auto_fixable,omitempty"`
	DiagnosisPath []*DiagnosisStep       `protobuf:"bytes,7,rep,name=diagnosis_path,json=diagnosisPath,proto3" json:"diagnosis_path,omitempty"`
	Escalated     bool                   `protobuf:"varint,8,opt,name=escalated,proto3" json:"escalated,omitempty"`
	Summary       string                 `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	// 机器可读的修复动作类型；suggested_fix 仅用于展示。
	FixType       string `protobuf:"bytes,10,opt,name=fix_type,json=fixType,proto3" json:"fix_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnoseResponse) Reset() {
	*x = DiagnoseResponse{}
	mi := &file_proto_diagnosis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnoseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnoseResponse) ProtoMessage() {}

func (x *DiagnoseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnoseResponse.ProtoReflect.Descriptor instead.
func (*DiagnoseResponse) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_proto_rawDescGZIP(), []int{1}
}

func (x *DiagnoseResponse) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *DiagnoseResponse) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *DiagnoseResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DiagnoseResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *DiagnoseResponse) GetSuggestedFix() string {
	if x != nil {
		return x.SuggestedFix
	}
	return ""
}

func (x *DiagnoseResponse) GetAutoFixable() bool {
	if x != nil {
		return x.AutoFixable
	}
	return false
}

func (x *DiagnoseResponse) GetDiagnosisPath() []*DiagnosisStep {
	if x != nil {
		return x.DiagnosisPath
	}
	return nil
}

func (x *DiagnoseResponse) GetEscalated() bool {
	if x != nil {
		return x.Escalated
	}
	return false
}

func (x *DiagnoseResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DiagnoseResponse) GetFixType() string {
	if x != nil {
		return x.FixType
	}
	return ""
}

type DiagnosisStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepNumber    int64                  `protobuf:"varint,1,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	Thought       string                 `protobuf:"bytes,2,opt,name=thought,proto3" json:"thought,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Observation   string                 `protobuf:"bytes,4,opt,name=observation,proto3" json:"observation,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	IsFinal       bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	FinalResult   *DiagnoseResponse      `protobuf:"bytes,7,opt,name=final_result,json=finalResult,proto3" json:"final_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosisStep) Reset() {
	*x = DiagnosisStep{}
	mi := &file_proto_diagnosis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosisStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisStep) ProtoMessage() {}

func (x *DiagnosisStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisStep.ProtoReflect.Descriptor instead.
func (*DiagnosisStep) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_proto_rawDescGZIP(), []int{2}
}

func (x *DiagnosisStep) GetStepNumber() int64 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *DiagnosisStep) GetThought() string {
	if x != nil {
		return x.Thought
	}
	return ""
}

func (x *DiagnosisStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DiagnosisStep) GetObservation() string {
	if x != nil {
		return x.Observation
	}
	return ""
}

func (x *DiagnosisStep) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DiagnosisStep) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *DiagnosisStep) GetFinalResult() *DiagnoseResponse {
	if x != nil {
		return x.FinalResult
	}
	return nil
}

type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RawData       string                 `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_proto_diagnosis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_proto_rawDescGZIP(), []int{3}
}

func (x *Evidence) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Evidence) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Evidence) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_diagnosis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_diagnosis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnosis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_diagnosis_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_diagnosis_proto protoreflect.FileDescriptor

const file_proto_diagnosis_proto_rawDesc = "" +
	"\n" +
	"\x15proto/diagnosis.proto\x12\n" +
	"watchtower\"\xf6\x02\n" +
	"\x0fDiagnoseRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12+\n" +
	"\x11alert_description\x18\x03 \x01(\tR\x10alertDescription\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12O\n" +
	"\falert_labels\x18\x05 \x03(\v2,.watchtower.DiagnoseRequest.AlertLabelsEntryR\valertLabels\x12%\n" +
	"\x0erelated_alerts\x18\x06 \x03(\tR\rrelatedAlerts\x12'\n" +
	"\x0falert_timestamp\x18\a \x01(\x03R\x0ealertTimestamp\x1a>\n" +
	"\x10AlertLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x03\n" +
	"\x10DiagnoseResponse\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x02 \x01(\tR\trootCause\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x120\n" +
	"\bevidence\x18\x04 \x03(\v2\x14.watchtower.EvidenceR\bevidence\x12#\n" +
	"\rsuggested_fix\x18\x05 \x01(\tR\fsuggestedFix\x12!\n" +
	"\fauto_fixable\x18\x06 \x01(\bR\vautoFixable\x12@\n" +
	"\x0ediagnosis_path\x18\a \x03(\v2\x19.watchtower.DiagnosisStepR\rdiagnosisPath\x12\x1c\n" +
	"\tescalated\x18\b \x01(\bR\tescalated\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x12\x19\n" +
	"\bfix_type\x18\n" +
	" \x01(\tR\afixType\"\xff\x01\n" +
	"\rDiagnosisStep\x12\x1f\n" +
	"\vstep_number\x18\x01 \x01(\x03R\n" +
	"stepNumber\x12\x18\n" +
	"\athought\x18\x02 \x01(\tR\athought\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12 \n" +
	"\vobservation\x18\x04 \x01(\tR\vobservation\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\x12?\n" +
	"\ffinal_result\x18\a \x01(\v2\x1c.watchtower.DiagnoseResponseR\vfinalResult\"_\n" +
	"\bEvidence\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\braw_data\x18\x03 \x01(\tR\arawData\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xeb\x01\n" +
	"\x10DiagnosisService\x12E\n" +
	"\bDiagnose\x12\x1b.watchtower.DiagnoseRequest\x1a\x1c.watchtower.DiagnoseResponse\x12J\n" +
	"\x0eDiagnoseStream\x12\x1b.watchtower.DiagnoseRequest\x1a\x19.watchtower.DiagnosisStep0\x01\x12D\n" +
	"\vHealthCheck\x12\x19.watchtower.HealthRequest\x1a\x1a.watchtower.HealthResponseB\x17Z\x15watchtower-lite/protob\x06proto3"

var (
	file_proto_diagnosis_proto_rawDescOnce sync.Once
	file_proto_diagnosis_proto_rawDescData []byte
)

func file_proto_diagnosis_proto_rawDescGZIP() []byte {
	file_proto_diagnosis_proto_rawDescOnce.Do(func() {
		file_proto_diagnosis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_diagnosis_proto_rawDesc), len(file_proto_diagnosis_proto_rawDesc)))
	})
	return file_proto_diagnosis_proto_rawDescData
}

var file_proto_diagnosis_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_diagnosis_proto_goTypes = []any{
	(*DiagnoseRequest)(nil),  // 0: watchtower.DiagnoseRequest
	(*DiagnoseResponse)(nil), // 1: watchtower.DiagnoseResponse
	(*DiagnosisStep)(nil),    // 2: watchtower.DiagnosisStep
	(*Evidence)(nil),         // 3: watchtower.Evidence
	(*HealthRequest)(nil),    // 4: watchtower.HealthRequest
	(*HealthResponse)(nil),   // 5: watchtower.HealthResponse
	nil,                      // 6: watchtower.DiagnoseRequest.AlertLabelsEntry
}
var file_proto_diagnosis_proto_depIdxs = []int32{
	6, // 0: watchtower.DiagnoseRequest.alert_labels:type_name -> watchtower.DiagnoseRequest.AlertLabelsEntry
	3, // 1: watchtower.DiagnoseResponse.evidence:type_name -> watchtower.Evidence
	2, // 2: watchtower.DiagnoseResponse.diagnosis_path:type_name -> watchtower.DiagnosisStep
	1, // 3: watchtower.DiagnosisStep.final_result:type_name -> watchtower.DiagnoseResponse
	0, // 4: watchtower.DiagnosisService.Diagnose:input_type -> watchtower.DiagnoseRequest
	0, // 5: watchtower.DiagnosisService.DiagnoseStream:input_type -> watchtower.DiagnoseRequest
	4, // 6: watchtower.DiagnosisService.HealthCheck:input_type -> watchtower.HealthRequest
	1, // 7: watchtower.DiagnosisService.Diagnose:output_type -> watchtower.DiagnoseResponse
	2, // 8: watchtower.DiagnosisService.DiagnoseStream:output_type -> watchtower.DiagnosisStep
	5, // 9: watchtower.DiagnosisService.HealthCheck:output_type -> watchtower.HealthResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_diagnosis_proto_init() }
func file_proto_diagnosis_proto_init() {
	if File_proto_diagnosis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_diagnosis_proto_rawDesc), len(file_proto_diagnosis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_diagnosis_proto_goTypes,
		DependencyIndexes: file_proto_diagnosis_proto_depIdxs,
		MessageInfos:      file_proto_diagnosis_proto_msgTypes,
	}.Build()
	File_proto_diagnosis_proto = out.File
	file_proto_diagnosis_proto_goTypes = nil
	file_proto_diagnosis_proto_depIdxs = nil
}
