// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3 compatible output
// source: proto/diagnosis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

const (
	DiagnosisService_Diagnose_FullMethodName       = "/watchtower.DiagnosisService/Diagnose"
	DiagnosisService_DiagnoseStream_FullMethodName = "/watchtower.DiagnosisService/DiagnoseStream"
	DiagnosisService_HealthCheck_FullMethodName    = "/watchtower.DiagnosisService/HealthCheck"
)

type DiagnosisServiceClient interface {
	Diagnose(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (*DiagnoseResponse, error)
	DiagnoseStream(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (DiagnosisService_DiagnoseStreamClient, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type diagnosisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosisServiceClient(cc grpc.ClientConnInterface) DiagnosisServiceClient {
	return &diagnosisServiceClient{cc}
}

func (c *diagnosisServiceClient) Diagnose(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (*DiagnoseResponse, error) {
	out := new(DiagnoseResponse)
	err := c.cc.Invoke(ctx, DiagnosisService_Diagnose_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosisServiceClient) DiagnoseStream(ctx context.Context, in *DiagnoseRequest, opts ...grpc.CallOption) (DiagnosisService_DiagnoseStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &DiagnosisService_ServiceDesc.Streams[0], DiagnosisService_DiagnoseStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &diagnosisServiceDiagnoseStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiagnosisService_DiagnoseStreamClient interface {
	Recv() (*DiagnosisStep, error)
	grpc.ClientStream
}

type diagnosisServiceDiagnoseStreamClient struct {
	grpc.ClientStream
}

func (x *diagnosisServiceDiagnoseStreamClient) Recv() (*DiagnosisStep, error) {
	m := new(DiagnosisStep)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *diagnosisServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DiagnosisService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DiagnosisServiceServer interface {
	Diagnose(context.Context, *DiagnoseRequest) (*DiagnoseResponse, error)
	DiagnoseStream(*DiagnoseRequest, DiagnosisService_DiagnoseStreamServer) error
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDiagnosisServiceServer()
}

type UnimplementedDiagnosisServiceServer struct{}

func (UnimplementedDiagnosisServiceServer) Diagnose(context.Context, *DiagnoseRequest) (*DiagnoseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Diagnose not implemented")
}
func (UnimplementedDiagnosisServiceServer) DiagnoseStream(*DiagnoseRequest, DiagnosisService_DiagnoseStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DiagnoseStream not implemented")
}
func (UnimplementedDiagnosisServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDiagnosisServiceServer) mustEmbedUnimplementedDiagnosisServiceServer() {}

type UnsafeDiagnosisServiceServer interface {
	mustEmbedUnimplementedDiagnosisServiceServer()
}

func RegisterDiagnosisServiceServer(s grpc.ServiceRegistrar, srv DiagnosisServiceServer) {
	s.RegisterService(&DiagnosisService_ServiceDesc, srv)
}

func _DiagnosisService_Diagnose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).Diagnose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DiagnosisService_Diagnose_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).Diagnose(ctx, req.(*DiagnoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosisService_DiagnoseStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiagnoseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiagnosisServiceServer).DiagnoseStream(m, &diagnosisServiceDiagnoseStreamServer{stream})
}

type DiagnosisService_DiagnoseStreamServer interface {
	Send(*DiagnosisStep) error
	grpc.ServerStream
}

type diagnosisServiceDiagnoseStreamServer struct {
	grpc.ServerStream
}

func (x *diagnosisServiceDiagnoseStreamServer) Send(m *DiagnosisStep) error {
	return x.ServerStream.SendMsg(m)
}

func _DiagnosisService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosisServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: DiagnosisService_HealthCheck_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosisServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var DiagnosisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchtower.DiagnosisService",
	HandlerType: (*DiagnosisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Diagnose", Handler: _DiagnosisService_Diagnose_Handler},
		{MethodName: "HealthCheck", Handler: _DiagnosisService_HealthCheck_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "DiagnoseStream", Handler: _DiagnosisService_DiagnoseStream_Handler, ServerStreams: true},
	},
	Metadata: "proto/diagnosis.proto",
}
